### ISSUE TITLE
All window decorators are #242424

### ISSUE THREAD

**Issue by wagnerkaue** [catppuccin/gtk#85] opened 2023-03-25 22:58 UTC
The window decorators are not matching the theme, they are all #242424, the only thing that change is the size 

Distro: EndeavourOS
Theme: Mocha
Installation: AUR package

**Expected behavior**
The color should be purple-ish, got #242424 dark gray instead

**Screenshots**
![image](https://user-images.githubusercontent.com/121360920/227746150-0be9444e-5dab-4e9e-a092-d361fceb2aaf.png) 
![image](https://user-images.githubusercontent.com/121360920/227746242-90d6c4ad-bc30-4961-89fa-7cf2ada5cbc3.png)

**Comment by npv12** [comment] 2023-03-26 11:20
Duplicate of #77

**Closed by npv12** 2023-03-26 11:20 UTC
