### ISSUE TITLE
Some QT windows have weird borders when not in full screen

### ISSUE THREAD

**Issue by brunobmello25** [catppuccin/gtk#95] opened 2023-05-12 23:47 UTC
**Describe the bug**
Some QT program windows have some weird border bug around them. This is happening with alacritty terminal and with "QT Assistant", so I'd assume it's something QT related.

**Mention your distribution and your theme version**
Fedora 38. I am using `Catppuccin-Mocha-Standard-Blue-Dark` but this also happens with `Catppuccin-Mocha-Standard-Lavender-Dark`

**Select how you installed the theme**
- [x] GitHub Releases

**Symlinked the gtk-4.0 folder?**
Have you symlinked the `gtk-4.0` folder as mentioned in the [README](https://github.com/catppuccin/gtk/blob/e907775723eb68a5628c1bcd718b9d822cea9aee/README.md?plain=1#L85-L93)?
Yes

**Expected behavior**
Should not have these borders on QT applications

**Screenshots**
![bug catppuccin](https://github.com/catppuccin/gtk/assets/29875060/0564c1ca-6f35-4ca2-820e-12cad671ae54)
![image](https://github.com/catppuccin/gtk/assets/29875060/5cb64b64-0b4a-4959-b28b-059b78cec31c)

**Comment by npv12** [comment] 2023-05-13 01:48
Duplicate of #92

**Closed by npv12** 2023-05-13 01:48 UTC
