### ISSUE TITLE
Brave Browser title bar gaps

### ISSUE THREAD

**Issue by dswapnil104** [catppuccin/gtk#73] opened 2023-01-25 10:41 UTC
## `Brave Browser` has title bar gaps when `Catppuccin` theme is applied : 
|#|Details||
|:-------------:|:-------------:|:-------------:|
|OS|Fedora37 (Workstation) x86_64|Kernel : 6.1.5-200.fc37|
|Display|WM : Mutter (3840x2160)|DE : Gnome 43.2|

> External display ran using **GPU**: NVIDIA GeForce GTX 1650 Mobile / Max-Q

_**Issue**_ : `BRAVE` browser (running under GDM/xorg/Dedicated GPU env) shows _artifacts_ and _flickering_ under the title bar and address bar owing to the `GAP` that in injected on usage of Catppuccin GTK theme.
- This issue is not observed with **Stock Browser Theme** 
- Neither is it observed with stock **Adwaita GTK Theme**

![Tweaks-Applied-GTK3/4](https://user-images.githubusercontent.com/66586954/214541641-b677fa00-dd8d-4b14-87e1-d2da10f3dae6.png)

![Title Bar Gaps](https://user-images.githubusercontent.com/66586954/214213327-b08c435e-c6ab-4bdf-b413-74b76331ba6a.png)

Intially, I assumed it to be my GPU rendering issues but later confirmed it was theme issue as the stock themes donot post this issue with the same hardware. 

[Similar Issue](https://github.com/vinceliuice/Colloid-gtk-theme/issues/97) is plaguing the Colloid GTK theme, the inspiration of Catppuccin.

To: Catppuccin Team : Thankyou for maintaining this awesome project and I would be more than willing to submit further needed inputs to fix the same.

**Comment by dswapnil104** [comment] 2023-01-25 10:41
Same issue reported on BRAVE github issues. [Here](https://github.com/brave/brave-browser/issues/22724)  
- Fix was delivered by Dracula Theme makers in this [commit](https://github.com/dracula/gtk/commit/43da99c96fc8f712689865837fb1593c9e6ca5af).

**Comment by ghostx31** [comment] 2023-01-25 10:51
I am unable to reproduce this issue on my system but someone in the Catppuccin Discord also brought this up. Are you using the v0.4.1 release?

Also, this seems like upstream bug. Thank you for opening the issue on Colloid's repository itself!

**Comment by dswapnil104** [comment] 2023-01-25 16:21
> I am unable to reproduce this issue on my system but someone in the Catppuccin Discord also brought this up. Are you using the v0.4.1 release?
> 
> Also, this seems like upstream bug. Thank you for opening the issue on Colloid's repository itself!

Yes I am running 0.4.1 of release.

**Comment by sgoudham** [comment] 2024-05-20 00:25
Hi :wave: 

Could you please confirm if this issue still exists in our latest release https://github.com/catppuccin/gtk/releases/tag/v0.7.5 ?

Thanks!

**Comment by nullishamy** [comment] 2024-05-21 01:28
![image](https://github.com/catppuccin/gtk/assets/99221043/bb444b04-2f7c-4478-9db6-7aa3c89a0277)
Cannot repro on `v1.0.0-rc3`

**Comment by nullishamy** [comment] 2024-05-26 19:29
Closing as resolved in later releases.

**Closed by nullishamy** 2024-05-26 19:29 UTC
Labels: bug, source:upstream, waiting on author, repro:denied
